all: 2_lit_review 6_design 8_ver appendices primitives

.PHONY: 2_lit_review 6_design 8_ver appendices primitives

2_lit_review:
	make -C $@/

6_design:
	make -C $@/

8_ver:
	make -C $@/

appendices:
	make -C $@/

primitives:
	make -C $@/
