stmt_example:
	merge -img -o stmt_1.dot pre_loop.dot stmt_0.dot
	merge -img -o stmt_2.dot list.dot stmt_1.dot
	merge -img -o stmt_3.dot if.dot stmt_2.dot
	merge -img -o stmt_4.dot if_return.dot stmt_3.dot
	merge -img -o stmt_5.dot if_else.dot stmt_4.dot
