all: clang_example control_flow_analysis_example decompilation_of_nested_primitives decompilation_of_post-test_loops ll2dot_example ll2go_example post_example restructure_example

.PHONY: clang_example control_flow_analysis_example decompilation_of_nested_primitives decompilation_of_post-test_loops ll2dot_example ll2go_example post_example restructure_example

clang_example:
	make -s -C $@/

control_flow_analysis_example:
	make -s -C $@/

decompilation_of_nested_primitives:
	make -s -C $@/

decompilation_of_post-test_loops:
	make -s -C $@/

ll2dot_example:
	make -s -C $@/

ll2go_example:
	make -s -C $@/

post_example:
	make -s -C $@/

restructure_example:
	make -s -C $@/
