all: clang_example ll2dot_example control_flow_analysis_example restructure_example post_example

.PHONY: clang_example ll2dot_example control_flow_analysis_example restructure_example post_example

clang_example:
	make -s -C $@/

ll2dot_example:
	make -s -C $@/

control_flow_analysis_example:
	make -s -C $@/

restructure_example:
	make -s -C $@/

post_example:
	make -s -C $@/
